# Generated by Django 5.2.8 on 2025-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('0 TO 20', '0 TO 20'), ('20 TO 50', '20 TO 50'), ('50 TO 100', '50 TO 100'), ('100 TO 500', '100 TO 500'), ('500 TO 1000', '500 TO 1000'), ('1000 TO 2000', '1000 TO 2000'), ('2000 TO 3000', '2000 TO 3000'), ('3000 TO 4000', '3000 TO 4000'), ('4000 TO 5000', '4000 TO 5000')], max_length=60)),
            ],
        ),
    ]
